version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    expose:
      - "5432"
    ports:
      - 5432:5432
    volumes:    
      - ./postgres-init-db.sh:/docker-entrypoint-initdb.d/postgres-init-db.sh
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.db
    networks:
      - dev-network

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - dev-network


volumes:
  postgres_data:

networks:
  dev-network:
    name: dev-network  # must match the actual name of the network created in the external file
























